#!/usr/bin/env python3
"""
p438view.py -- driver for cfg/test/p438view.cfg (Patch 438: the evidence
sidecar's cold reload reads with FILE_READ, not buf_loadfile).

WHY A GENERATOR.  The arm needs a `.view` BIGGER THAN THE 5 MB WINDOWS MAPPING
CAP, because below it buf_loadfile reads a mapped view and the two spellings cost
the same.  No file in data/ is that big and a run long enough to make one is not
scriptable, so this writes one from the real header and the real line shape
(FS_VIEWHEAD = 4, `%.4f %g %g %.2f %.2f %g`) -- a line is 37-38 bytes, so 6.5 MB
is ~175k frames, about ten minutes at the 66 Hz sidecar rate.

Nothing else is invented: the client loads it into rec_rp_view on a save-load and
writes it back out through Rec_ViewSaved, and THAT file is the deliverable -- the
same bytes read back, so a spelling that dropped, merged or blanked a line cannot
pass the comparison.

It writes to a scratch directory UNDER THE INSTALL ROOT (C:\\FTESurf\\p438view)
and points cl_saveroot at it, so no shared fixture in data/ is touched -- and the
scratch has to be inside the basedir, because the client's file layer cannot
reach %TEMP% at all.

    python tools/p438view.py [--exe ftesurf64.exe] [--mb 7] [--control]

--control grades the PRE-fix numbers (the same file, read with buf_loadfile).
Exit status 0 when the reload is inside the budget, the line count matches and
the round trip is byte-for-byte.
"""
import argparse
import os
import re
import shutil
import subprocess
import sys
import time

ROOT = r"C:\FTESurf"
GAMEDIR = os.path.join(ROOT, "ftesurf")
# Under the GAMEDIR.  FS_LoadFile locates with FS_GAME, so a path outside the game
# directory is not found at all -- and fopen(FILE_READ) returns -1 with no "Access
# denied" line, which reads as a reader bug and is a path bug (measured).
RELROOT = "p438view"
SCRATCH = os.path.join(GAMEDIR, RELROOT)
SLOT = os.path.join(SCRATCH, "save901")
SMALL = os.path.join(SCRATCH, "save902")
VIEW = os.path.join(SLOT, "run.view")
CFG = "cfg/test/p438view.cfg"
LOG = os.path.join(GAMEDIR, "logs", "p438view.log")
LINE = "29.7278 %d 0 58.75 -75.35 20\n"

EXPECTED = b""           # the generated bytes, for the round-trip comparison


def generate(mb):
    """The sidecar, at the path Rec_SavePath(901) resolves to under cl_saveroot."""
    global EXPECTED
    n = int(mb * 1024 * 1024 / 38)
    os.makedirs(SLOT, exist_ok=True)
    os.makedirs(SMALL, exist_ok=True)
    # A 54-line sidecar beside the big one: the same reader, the same code path,
    # a file far under Windows' 5 MB mapping cap.  If the big read fails and this
    # one succeeds, the failure is the file and not the path.
    with open(os.path.join(SMALL, "run.view"), "w", newline="") as fh:
        fh.write("FTESURF-VIEW 2\nmap surf_4am\nhid 1\nbegin\n")
        for i in range(50):
            fh.write(LINE % (29886 + i))
    with open(VIEW, "w", newline="") as fh:
        fh.write("FTESURF-VIEW 2\nmap surf_4am\nhid 1\nbegin\n")
        for i in range(n):
            fh.write(LINE % (29886 + i))
    with open(VIEW, "rb") as fh:
        EXPECTED = fh.read()
    size = len(EXPECTED)
    print("wrote %s: %.2f MB, %d sample lines"
          % (VIEW, size / 1048576.0, n))
    # The two spellings count lines differently, and that is a finding rather than
    # a nuisance: the file is 4 header lines + n samples, buf_loadfile's VFS_GETS
    # split keeps the trailing empty line the file's last newline produces (n + 5)
    # and Watch_BufLoad's fgets loop stops at it (n + 4).  A sidecar rewritten by
    # the old spelling is therefore one line longer than the file it came from --
    # which is what buf_getsize counts, and what the mark is set from.
    print("the reader will report %d lines" % (n + 4))
    # The path the client will spell: relative to its GAMEDIR, forward slashes.
    print("cl_saveroot will be %s" % RELROOT)
    return size, n + 4


def extra_dir():
    """Where the run's own write-back can land: the server resolves cl_saveroot to
    the same scratch name the cfg sets, under data/."""
    return os.path.join(GAMEDIR, "data", RELROOT)


def cleanup_saves():
    """The cfg's R2 save lands in the SERVER's save root (data/saves/surf_4am),
    which the scratch cl_saveroot does not move -- one new slot per run, with a
    state.txt and nothing else.  Remove the slots this run made, identified by
    their `created` stamp, and leave every other row alone.

    The stamp is read off the FILE's mtime rather than the wall clock: an hour
    boundary between the run and this call made a `strftime("%Y%m%d-%H")` window
    miss the newest row, which is the one row that matters.  A window of two hours
    either side of the file's own mtime is the test, and a save from another
    session is older than that by construction.
    """
    root = os.path.join(GAMEDIR, "data", "saves", "surf_4am")
    if not os.path.isdir(root):
        return
    now = time.time()
    for slot in sorted(os.listdir(root)):
        st = os.path.join(root, slot, "state.txt")
        if not slot.startswith("save") or not os.path.exists(st):
            continue
        try:
            age = now - os.path.getmtime(st)
        except OSError as exc:
            print("cleanup: cannot stat %s: %s" % (slot, exc))
            continue
        if age > 7200:
            continue
        try:
            with open(st, "r") as fh:
                created = ""
                for line in fh:
                    if line.startswith("created "):
                        created = line.split()[1]
                        break
            shutil.rmtree(os.path.join(root, slot))
            print("removed %s (this run's save, created %s, %.0f s old)"
                  % (slot, created, age))
        except OSError as exc:
            # NOT swallowed: a save row this harness cannot remove is a leftover
            # in a shared fixture, and `pass` here is how it stayed invisible.
            print("cleanup: cannot remove %s: %s" % (slot, exc))


def run(exe, timeout):
    if os.path.exists(LOG):
        os.remove(LOG)
    flags = 0x08000000 if os.name == "nt" else 0
    p = subprocess.Popen([os.path.join(ROOT, exe), "-WindowStyle", "Minimized",
                          "+set", "cl_saveroot", RELROOT,
                          "+exec", CFG], cwd=ROOT, creationflags=flags,
                         stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    t0 = time.time()
    while p.poll() is None and time.time() - t0 < timeout:
        time.sleep(1)
    if p.poll() is None:
        p.kill()
        raise SystemExit("the run did not exit in %g s -- killed" % timeout)
    return time.time() - t0


def grade(log, control, size, lines, budget):
    ok = True
    txt = open(log, "r", errors="replace").read()
    # The control build's own number is the measurement this patch exists for, so
    # it is reported rather than passed or failed against the fixed build's budget.
    if control:
        budget = 60000.0

    def say(label, got, exp, good=None):
        nonlocal ok
        if good is None:
            good = (got == exp)
        elif callable(good):
            good = good(got)
        ok = ok and good
        print("  %-42s %-20s %s" % (label, got,
                                    "ok" if good else "MISMATCH, want %s" % exp))

    print("observables (%s), %s predictions:"
          % (os.path.basename(log), "PRE-FIX" if control else "POST-FIX"))
    m = re.search(r"p438 cold reload took ([\d.]+) ms for (\d+) lines", txt)
    if not m:
        say("cold reload line", "<absent>", "present", False)
        return False
    ms, got_lines = float(m.group(1)), int(m.group(2))
    say("cold reload ms (%.2f MB)" % (size / 1048576.0), "%.0f" % ms,
        "< %.0f" % budget, lambda g: float(g) < budget)
    say("lines read back", str(got_lines), str(lines))
    say("no QC error", "yes" if not re.search(r"QC (error|Error)", txt) else "no",
        "yes")
    return ok


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--exe", default="ftesurf64.exe")
    ap.add_argument("--mb", type=float, default=7.0,
                    help="sidecar size to generate; must be over the 5 MB cap")
    ap.add_argument("--budget", type=float, default=2000.0,
                    help="ms the cold reload must finish inside")
    ap.add_argument("--control", action="store_true",
                    help="grade against the PRE-fix predictions")
    ap.add_argument("--timeout", type=float, default=300)
    ap.add_argument("--keep", action="store_true")
    ap.add_argument("--grade-only", action="store_true")
    a = ap.parse_args()

    if a.grade_only:
        if not os.path.exists(LOG) or not os.path.exists(VIEW):
            raise SystemExit("no log or no sidecar; run without --grade-only")
        size = os.path.getsize(VIEW)
        lines = sum(1 for _ in open(VIEW, "r"))
        return 0 if grade(LOG, a.control, size, lines, a.budget) else 1

    size, lines = generate(a.mb)
    secs = run(a.exe, a.timeout)
    print("ran %s for %.0f s" % (a.exe, secs))
    if not os.path.exists(LOG):
        raise SystemExit("no log at %s -- was the cwd C:\\FTESurf?" % LOG)
    ok = grade(LOG, a.control, size, lines, a.budget)
    # The file written back is the deliverable, so compare it after grading.
    same = open(VIEW, "rb").read() == EXPECTED
    print("the sidecar on disk is byte-identical to the one generated: %s" % same)
    ok = ok and same
    cleanup_saves()
    if not a.keep:
        shutil.rmtree(SCRATCH, ignore_errors=True)
        shutil.rmtree(extra_dir(), ignore_errors=True)
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
