"""Cross-check SV_PropHasPhy against the ENGINE's own filesystem search.

SV_SpawnProp now applies Source's rule -- a prop asking for VPhysics collision
collides against its model's .phy VCollide or against nothing -- and the answer
comes from a QC `fopen`.  That is one code path.  This tool asks the same question
down a completely different one: `flocate`, the engine's console file search
(common/fs.c COM_Locate_f, via FS_FLocateFile), written in C and reached through
the console rather than through a QC builtin.  If the two disagree about any path,
the probe is wrong and props are being made solid or non-solid for no reason.

WHY IT RUNS PER MAP AND NOT ONCE.  A custom map can ship its models inside its own
BSP pak lump, so a .phy that exists while that map is loaded does not exist after
it unloads.  Flocating the whole set from one map would report "Not found" for
every embedded model and read as a probe failure.  Each map's paths are therefore
flocated WITH THAT MAP LOADED, in the same order the arm loaded them.

  python tools/p458phy.py --gen    reads ftesurf/logs/p458prop.log (the phyprobe
                                   lines) and writes cfg/test/p458phy.cfg
  python tools/p458phy.py          reads ftesurf/logs/p458phy.log and diffs

Three verdicts.  A path neither side could resolve is NOT DEMONSTRATED, not a
failure: see the fail-safe note in SV_PropHasPhy.
"""
import os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
LOGS = os.path.join(ROOT, 'ftesurf', 'logs')
CFG = os.path.join(ROOT, 'ftesurf', 'cfg', 'test', 'p458phy.cfg')

TS = re.compile(r'^\d{4}-\d\d-\d\d \d\d:\d\d:\d\d ')
SECTION = re.compile(r'^={4} M\d (\S+) ')
PROBE = re.compile(r'^phyprobe ([01]) (\S+)$')
MARK = re.compile(r'^PHYQ (\S+)$')
MAPMARK = re.compile(r'^PHYMAP (\S+)$')


def readprobes(logname):
    """{map: {path: verdict}} in load order, from the arm's own dprints."""
    path = os.path.join(LOGS, logname)
    if not os.path.exists(path):
        return None, "no log at %s" % path
    out = []
    cur = None
    for ln in open(path, encoding='utf-8', errors='replace'):
        ln = TS.sub('', ln.strip())
        m = SECTION.match(ln)
        if m:
            cur = (m.group(1), {})
            out.append(cur)
            continue
        if cur is None:
            continue
        m = PROBE.match(ln)
        if m:
            cur[1][m.group(2)] = int(m.group(1))
    return [(k, v) for k, v in out if v], None


def gen():
    maps, err = readprobes('p458prop.log')
    if err:
        print(err)
        return 2
    if not maps:
        print("no phyprobe lines -- run cfg/test/p458prop.cfg on a build with the probe")
        return 2
    L = []
    L.append("// P458PHY -- GENERATED by tools/p458phy.py --gen.  Do not hand-edit.")
    L.append("//")
    L.append("// Asks the engine's own file search (flocate, common/fs.c) for every .phy")
    L.append("// path SV_PropHasPhy probed, with the SAME MAP LOADED -- a custom map can ship")
    L.append("// its models in its own BSP pak lump, so these paths are not global facts.")
    L.append("// flocate prints no filename when it finds one, hence the echo before each.")
    L.append("log_enable 1")
    L.append("log_dir logs")
    L.append("log_name p458phy")
    L.append("developer 0")
    L.append("cl_idlefps 0")
    L.append("fs_missingwarn 0")
    L.append("con_notifylines 0")
    L.append("sv_port 27709")
    L.append("vid_fullscreen 0")
    L.append("waitms 5000")
    L.append("menu_restart")
    L.append("ui_close")
    L.append("waitms 1200")
    total = 0
    for mapname, probes in maps:
        L.append("")
        L.append("map %s" % mapname)
        L.append("waitmap 3600")
        L.append("waitms 2000")
        L.append("echo PHYMAP %s" % mapname)
        for p in sorted(probes):
            L.append("echo PHYQ %s" % p)
            L.append("flocate %s" % p)
            total += 1
        L.append("waitms 300")
    L.append("")
    L.append("quit")
    with open(CFG, 'w', encoding='utf-8', newline='\n') as f:
        f.write("\n".join(L) + "\n")
    print("wrote %s -- %d map(s), %d path(s)" % (CFG, len(maps), total))
    return 0


def grade():
    maps, err = readprobes('p458prop.log')
    if err:
        print(err)
        return 2
    want = {}
    for mapname, probes in maps:
        want.setdefault(mapname, {}).update(probes)

    path = os.path.join(LOGS, 'p458phy.log')
    if not os.path.exists(path):
        print("no log at %s -- run cfg/test/p458phy.cfg (generate it with --gen first)" % path)
        return 2

    # Pair each `PHYQ <path>` with the flocate reply that follows it.
    got = {}
    curmap = None
    pending = None
    for ln in open(path, encoding='utf-8', errors='replace'):
        ln = TS.sub('', ln.rstrip())
        s = ln.strip()
        m = MAPMARK.match(s)
        if m:
            curmap = m.group(1)
            continue
        m = MARK.match(s)
        if m:
            pending = m.group(1)
            continue
        if pending is None:
            continue
        if s.startswith('Not found'):
            got.setdefault(curmap, {})[pending] = 0
            pending = None
        elif s.startswith('Inside ') or s.startswith('File is '):
            got.setdefault(curmap, {})[pending] = 1
            pending = None

    rc = 0
    checked = agree = 0
    nd = []
    disagree = []
    for mapname, probes in want.items():
        g = got.get(mapname, {})
        for p, v in sorted(probes.items()):
            if p not in g:
                nd.append((mapname, p))
                continue
            checked += 1
            if g[p] == v:
                agree += 1
            else:
                disagree.append((mapname, p, v, g[p]))

    print("p458phy -- SV_PropHasPhy (QC fopen) vs flocate (engine C)")
    print()
    for mapname in sorted(want):
        g = got.get(mapname, {})
        mine = want[mapname]
        both = [p for p in mine if p in g]
        bad = [p for p in both if g[p] != mine[p]]
        haz = sum(1 for p in both if mine[p])
        print("  %-24s %4d path(s) compared, %4d has-.phy, %4d no-.phy, %d disagree%s"
              % (mapname, len(both), haz, len(both) - haz, len(bad),
                 "" if not bad else "  <-- " + bad[0]))
    print()
    if disagree:
        rc = 1
        print("DISAGREEMENTS (QC verdict / flocate verdict):")
        for mapname, p, v, gv in disagree[:20]:
            print("  %s  %s  qc=%d flocate=%d" % (mapname, p, v, gv))
    if nd:
        print("NOT COMPARED: %d path(s) had no flocate reply (regenerate the cfg)" % len(nd))
        for mapname, p in nd[:5]:
            print("  %s  %s" % (mapname, p))
    print()
    if not checked:
        print("NOT DEMONSTRATED -- nothing was compared.")
        return 2
    if rc == 0:
        print("PASS -- %d of %d path(s) agree on both code paths. The .phy probe is"
              "\n        answering the same question the engine's filesystem does." % (agree, checked))
    else:
        print("FAIL -- %d of %d disagree." % (len(disagree), checked))
    return rc


if __name__ == '__main__':
    sys.exit(gen() if '--gen' in sys.argv else grade())
